name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resolver:
          [
            "lts-18.0",
            "lts-16.31",
            "lts-14.27",
            "lts-12.26",
            "lts-11.22",
            "lts-9.21",
          ]
        include:
          - resolver: "lts-18.0"
            ghc: "8.10.4"
          - resolver: "lts-16.31"
            ghc: "8.8.4"
          - resolver: "lts-14.27"
            ghc: "8.6.5"
          - resolver: "lts-12.26"
            ghc: "8.4.4"
          - resolver: "lts-11.22"
            ghc: "8.2.2"
          - resolver: "lts-9.21"
            ghc: "8.0.2"

    steps:
      - name: Setup GHC
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true

      - name: Clone project
        uses: actions/checkout@v2.3.4

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      # This entirely avoids the caching of a GHC version.
      - name: Build and run tests
        run: "stack test --fast --no-terminal --resolver=${{ matrix.resolver }} --system-ghc"
